spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login_security?autoReconnect=true&serverTimezone=UTC
    username: root
    password: plus&data51

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

property:
  test:
    name: property depth test
